{"name": "Успешная аутентификация под валидными данными", "status": "passed", "start": 1719739886229, "stop": 1719739886291, "uuid": "bbf2ac7e-1a77-481f-827b-76498d0a701b", "historyId": "dcbb13e4430486c898e42c89b93bb88c", "testCaseId": "dcbb13e4430486c898e42c89b93bb88c", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_valid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "PC-MASTER"}, {"name": "thread", "value": "12584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}